### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by votacom** [morepaolo/roundcube-pop3fetcher#12]
WIth these tweaks, I have made the plugin work with PostgreSQL backend:

Add `SQL/postgresql.sql` with contents:

<pre><code>DROP INDEX IF EXISTS user_id_fk_accounts;

DROP TABLE IF EXISTS pop3fetcher_accounts;

DROP SEQUENCE IF EXISTS pop3fetcher_seq;

CREATE SEQUENCE pop3fetcher_seq
  START WITH 23;

CREATE TABLE  pop3fetcher_accounts (
  pop3fetcher_id INTEGER PRIMARY KEY DEFAULT nextval('pop3fetcher_seq'),
  pop3fetcher_email varchar(128) NOT NULL,
  pop3fetcher_username varchar(128) NOT NULL,
  pop3fetcher_password varchar(128) NOT NULL,
  pop3fetcher_serveraddress varchar(128) NOT NULL,
  pop3fetcher_serverport varchar(128) NOT NULL,
  pop3fetcher_ssl varchar(10) DEFAULT '0',
  pop3fetcher_leaveacopyonserver BOOLEAN DEFAULT FALSE,
  user_id INTEGER NOT NULL DEFAULT '0',
  last_check INTEGER NOT NULL DEFAULT '0',
  last_uidl varchar(70) DEFAULT NULL,
  update_lock BOOLEAN NOT NULL DEFAULT FALSE,
  pop3fetcher_provider varchar(128) DEFAULT NULL,
  default_folder varchar(128) DEFAULT NULL
);

CREATE INDEX user_id_fk_accounts ON pop3fetcher_accounts (
  user_id
);

ALTER SEQUENCE pop3fetcher_seq OWNED BY pop3fetcher_accounts.pop3fetcher_id;</code></pre>

Instead of running the mysql or sqlite script as stated in the readme, run this script.

In `pop3fetcher.php`, lines 291-295 and 574-584, change every occurence of `=true` and `=false` to `="true"` and `="false"`, respictively. (MySQL seems to understand allocations of empty strings to `tinyint(1)` fields, but PostgreSQL does not for `boolean` fields).

Nevertheless, I think I will get rid of the plugin soon - fetchmail seems a more reliable and secure way for my purposes.

**Comment by theqkash** [comment]
It has been added to master branch for now.

Thank you.
