### ISSUE TITLE
Check for New Messages every 60 seconds

### ISSUE THREAD

**Issue by davetanguay** [morepaolo/roundcube-pop3fetcher#13]
I also posted this at http://www.roundcubeforum.net/index.php/topic,15363.msg50087.html#msg50087 since I'm not sure if this is a plugin or Roundcube issue

I'm using Roundcube 0.9.5 in the latest release of CPanel.

I also have the pop3fetcher plugin installed and it is working.

The problem is Roundcube only checks for new emails in the external POP mailbox if I click the Refresh button in Roundcube. It does not automatically check for new emails in the external POP mailbox every 60 seconds. It does check for new emails which are sent directly to the mailbox every 60 seconds... just not external mailbox messages.

I always must click REFRESH in Roundcube for it to check for new emails in the external POP mailbox.

I would like it setup to automatically check emails in the external POP mailbox every 60 seconds.

It seems the 60 second new message check is related to the file at /program/steps/mail/getunread.inc and the REFRESH button in Roundcube is related to /program/steps/mail/check_recent.inc 

I've messed around with those files and still can't figure out how to enabled an automatic check of external mailboxes. 

I notice in check_recent.inc it had the following lines of code which I thought I could just add to getunread.inc which would take care of this but I still can't get it to work.
# 

// Control folders list from a plugin
$plugin      = $RCMAIL->plugins->exec_hook('check_recent', array('folders' => $a_mailboxes, 'all' => $check_all));
# $a_mailboxes = $plugin['folders'];

towards the bottom of check_recent.inc I see the following as well which I tried to add too:
# 
# $RCMAIL->plugins->exec_hook('refresh', array());

Still no luck.

Any help would be greatly appreciated.

-Dave T.

**Comment by ssdnvv** [comment]
I'm using Roundcube v. 1.1.2 and pop3fetcher v.1.9
Unfortunately I got the same Problem - If I sent an email to a mail-account that is set to be collected via pop3fetcher, the Mail does not get fetched automatically - until I use the "refresh"-Button within Roundcube...
