### ISSUE TITLE
undefined method rcmail::imap_connect()

### ISSUE THREAD

**Issue by radiomix** [morepaolo/roundcube-pop3fetcher#18]
I get an error on `roundcube-1.2-beta` with plugin pop3fetcher:
```
 Call to undefined method rcmail::imap_connect() in /var/www/roundcubemail-1.2-beta/plugins/pop3fetcher/pop3fetcher.php on line 121
```
This is my installation:

Roundcube Webmail 1.2-beta

Copyright © 2005-2015, The Roundcube Dev Team

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Some exceptions for skins & plugins apply.
Installed plugins
Plugin 	Version 	License 	Source
archive 	2.3 	GPLv3+ 	
Attachment Reminder 	1.1 	GPLv3+ 	
calendar 		AGPLv3 	Download
chbox 	0.2.4 	GNU GPLv3+ 	
emoticons 	2.0 	GPLv3+ 	
filesystem_attachments 	1.0 	GPLv3+ 	
jqueryui 	1.10.4 	GPLv3+ 	
libcalendaring 		AGPLv3 	Download
markasjunk 	1.2 	GPLv3+ 	
odfviewer 	0.2 	GNU AGPL 	Download
pdfviewer 	0.1 	GNU AGPL 	Download
pop3fetcher 	-- 		
show_additional_headers 	2.0 	GPLv3+ 	
tasklist 		AGPLv3 	Download
zipdownload 	3.0 	GPLv3+ 	

It seems the definition of the method disapeared in `roundcube-1.2-beta`.

**Comment by theqkash** [comment]
The same in 1.2 / 1.2.1

Authors seems to not to care abut it...

**Comment by theqkash** [comment]
I've fixed that.

You should open file pop3fetcher.php in plugin directory and make changes.

Replace all:
`imap_connect()`

to
`storage_connect()`

Pop3fetcher seems to work after that.

**Comment by radiomix** [comment]
@theqkash Thank you for hint. I changed the function names and it worked like a charm.
