### ISSUE TITLE
Unencrypted Passwords in the MySQL Database

### ISSUE THREAD

**Issue by ghost** [morepaolo/roundcube-pop3fetcher#8]
I found out that all accounts have been saved without encrypting the passwords in the database. The administrator or a cracker has the possibility to take over these accounts. If you are the only one on the e-mail server that should be OK, but if you have more users then you, the passwords should be encrypted. i think the encryption have not to be very hard, but there should be an encryption.

**Comment by gloony** [comment]
This Issue is closed but not implemented. I made it on this commit: #24
